- name: configure interface up/down on routers.
  cisco.ios.ios_interfaces:
    config:
    - name: "{{ item.name }}"
      enabled: "{{ item.enabled | default('true') }}"
    state: replaced
  loop: "{{ interfaces }}"
  loop_control:
    label: "{{ item.name }}"